import { __ } from '@wordpress/i18n';
import { useBlockProps, InspectorControls, __experimentalLinkControl as LinkControl } from '@wordpress/block-editor';
import { PanelBody, TextControl, TextareaControl } from '@wordpress/components';
import { registerBlockType } from '@wordpress/blocks';
import metadata from './block.json';
import { BackgroundLayoutPanel, getBackgroundStyle, getOverlayStyle } from '../shared/background-layout-controls';
import { getUrlFromLinkValue } from '../shared/link-utils';
import './editor.css';
import './style.css';

function Plan({ title, text, price, buttonLabel, buttonUrl }) { return <div className="item"><div className="item-wrapper"><h4 className="item-title mbr-fonts-style display-5"><strong>{title}</strong></h4><p className="item-text mbr-fonts-style display-4">{text}</p><p className="item-price mbr-fonts-style display-2"><strong>{price}</strong></p><div className="mbr-section-btn item-btn">{buttonLabel&&<a href={buttonUrl||'#'} className="btn btn-black display-7">{buttonLabel}</a>}</div></div></div>; }

function Edit({ attributes, setAttributes }) {
  const { backgroundImageEnabled, backgroundImageUrl, overlayEnabled, overlayColor, overlayOpacity, parallax, fullscreen, label, heading, text, p1Title, p1Price, p1Text, p1ButtonLabel, p1ButtonUrl, p2Title, p2Price, p2Text, p2ButtonLabel, p2ButtonUrl, p3Title, p3Price, p3Text, p3ButtonLabel, p3ButtonUrl } = attributes;
  const className=['restatify-pricing-block', backgroundImageEnabled!==false&&parallax?'is-parallax':'', fullscreen?'is-fullscreen':''].join(' '); const style=getBackgroundStyle(backgroundImageEnabled, backgroundImageUrl); const overlayStyle=getOverlayStyle(overlayEnabled, overlayColor, overlayOpacity);
  return <div {...useBlockProps()}><InspectorControls><BackgroundLayoutPanel attributes={attributes} setAttributes={setAttributes}/><PanelBody title={__('Content','restatify-base')} initialOpen={false}><TextControl label={__('Label','restatify-base')} value={label} onChange={(v)=>setAttributes({label:v})}/><TextControl label={__('Heading','restatify-base')} value={heading} onChange={(v)=>setAttributes({heading:v})}/><TextareaControl label={__('Text','restatify-base')} value={text} onChange={(v)=>setAttributes({text:v})}/></PanelBody>{[['1',p1Title,p1Text,p1Price,p1ButtonLabel,p1ButtonUrl],['2',p2Title,p2Text,p2Price,p2ButtonLabel,p2ButtonUrl],['3',p3Title,p3Text,p3Price,p3ButtonLabel,p3ButtonUrl]].map((p)=><PanelBody key={p[0]} title={__('Plan ','restatify-base')+p[0]} initialOpen={false}><TextControl label={__('Title','restatify-base')} value={p[1]} onChange={(v)=>setAttributes({[`p${p[0]}Title`]:v})}/><TextareaControl label={__('Text','restatify-base')} value={p[2]} onChange={(v)=>setAttributes({[`p${p[0]}Text`]:v})}/><TextControl label={__('Price','restatify-base')} value={p[3]} onChange={(v)=>setAttributes({[`p${p[0]}Price`]:v})}/><TextControl label={__('Button label','restatify-base')} value={p[4]} onChange={(v)=>setAttributes({[`p${p[0]}ButtonLabel`]:v})}/><p>{__('Button link','restatify-base')}</p><LinkControl value={{url:p[5]||''}} onChange={(n)=>setAttributes({[`p${p[0]}ButtonUrl`]:getUrlFromLinkValue(n)})} settings={[]}/></PanelBody>)}</InspectorControls><div className={className} style={style}>{backgroundImageEnabled!==false&&overlayEnabled&&<div className="restatify-pricing-bg-overlay" style={overlayStyle} aria-hidden="true"></div>}<div className="container"><div className="row justify-content-center"><div className="col-12 col-lg-11"><div className="content-wrapper"><p className="mbr-label mbr-fonts-style display-4">{label}</p><h2 className="mbr-section-title mbr-fonts-style display-2"><strong>{heading}</strong></h2><p className="mbr-text mbr-fonts-style display-4">{text}</p><div className="items-wrapper"><Plan title={p1Title} text={p1Text} price={p1Price} buttonLabel={p1ButtonLabel} buttonUrl={p1ButtonUrl}/><Plan title={p2Title} text={p2Text} price={p2Price} buttonLabel={p2ButtonLabel} buttonUrl={p2ButtonUrl}/><Plan title={p3Title} text={p3Text} price={p3Price} buttonLabel={p3ButtonLabel} buttonUrl={p3ButtonUrl}/></div></div></div></div></div></div></div>;
}

function Save({ attributes }) {
  const { backgroundImageEnabled, backgroundImageUrl, overlayEnabled, overlayColor, overlayOpacity, parallax, fullscreen, label, heading, text, p1Title, p1Price, p1Text, p1ButtonLabel, p1ButtonUrl, p2Title, p2Price, p2Text, p2ButtonLabel, p2ButtonUrl, p3Title, p3Price, p3Text, p3ButtonLabel, p3ButtonUrl } = attributes;
  const overlayStyle=getOverlayStyle(overlayEnabled, overlayColor, overlayOpacity); const blockProps=useBlockProps.save({className:['restatify-pricing-block', backgroundImageEnabled!==false&&parallax?'is-parallax':'', fullscreen?'is-fullscreen':''].join(' '), style:getBackgroundStyle(backgroundImageEnabled, backgroundImageUrl)});
  return <div {...blockProps}>{backgroundImageEnabled!==false&&overlayEnabled&&<div className="restatify-pricing-bg-overlay" style={overlayStyle} aria-hidden="true"></div>}<div className="container"><div className="row justify-content-center"><div className="col-12 col-lg-11"><div className="content-wrapper"><p className="mbr-label mbr-fonts-style display-4">{label}</p><h2 className="mbr-section-title mbr-fonts-style display-2"><strong>{heading}</strong></h2><p className="mbr-text mbr-fonts-style display-4">{text}</p><div className="items-wrapper"><Plan title={p1Title} text={p1Text} price={p1Price} buttonLabel={p1ButtonLabel} buttonUrl={p1ButtonUrl}/><Plan title={p2Title} text={p2Text} price={p2Price} buttonLabel={p2ButtonLabel} buttonUrl={p2ButtonUrl}/><Plan title={p3Title} text={p3Text} price={p3Price} buttonLabel={p3ButtonLabel} buttonUrl={p3ButtonUrl}/></div></div></div></div></div></div>;
}

registerBlockType(metadata.name,{...metadata,edit:Edit,save:Save});
