import { __ } from '@wordpress/i18n';
import { useBlockProps, InspectorControls, MediaUpload, MediaUploadCheck } from '@wordpress/block-editor';
import { PanelBody, TextControl, Button } from '@wordpress/components';
import { registerBlockType } from '@wordpress/blocks';
import metadata from './block.json';
import { BackgroundLayoutPanel, getBackgroundStyle, getOverlayStyle } from '../shared/background-layout-controls';
import './editor.css';
import './style.css';

function ContactItem({ title, value }) { return <div className="item"><div className="item-wrapper"><h4 className="item-title mbr-fonts-style display-4">{title}</h4><p className="item-text mbr-fonts-style display-7"><strong>{value}</strong></p></div></div>; }

function Edit({ attributes, setAttributes }) {
  const { backgroundImageEnabled, backgroundImageUrl, overlayEnabled, overlayColor, overlayOpacity, parallax, fullscreen, label, heading, phoneLabel, phoneValue, emailLabel, emailValue, locationLabel, locationValue, imageUrl } = attributes;
  const className=['restatify-contact-block', backgroundImageEnabled!==false&&parallax?'is-parallax':'', fullscreen?'is-fullscreen':''].join(' '); const style=getBackgroundStyle(backgroundImageEnabled, backgroundImageUrl); const overlayStyle=getOverlayStyle(overlayEnabled, overlayColor, overlayOpacity);
  return <div {...useBlockProps()}><InspectorControls><BackgroundLayoutPanel attributes={attributes} setAttributes={setAttributes}/><PanelBody title={__('Content','restatify-base')} initialOpen={false}><TextControl label={__('Label','restatify-base')} value={label} onChange={(v)=>setAttributes({label:v})}/><TextControl label={__('Heading','restatify-base')} value={heading} onChange={(v)=>setAttributes({heading:v})}/></PanelBody><PanelBody title={__('Details','restatify-base')} initialOpen={false}><TextControl label={__('Phone label','restatify-base')} value={phoneLabel} onChange={(v)=>setAttributes({phoneLabel:v})}/><TextControl label={__('Phone value','restatify-base')} value={phoneValue} onChange={(v)=>setAttributes({phoneValue:v})}/><TextControl label={__('Email label','restatify-base')} value={emailLabel} onChange={(v)=>setAttributes({emailLabel:v})}/><TextControl label={__('Email value','restatify-base')} value={emailValue} onChange={(v)=>setAttributes({emailValue:v})}/><TextControl label={__('Location label','restatify-base')} value={locationLabel} onChange={(v)=>setAttributes({locationLabel:v})}/><TextControl label={__('Location value','restatify-base')} value={locationValue} onChange={(v)=>setAttributes({locationValue:v})}/></PanelBody><PanelBody title={__('Image','restatify-base')} initialOpen={false}><MediaUploadCheck><MediaUpload onSelect={(m)=>setAttributes({imageUrl:m?.url||''})} allowedTypes={['image']} value={imageUrl} render={({open})=><Button variant="secondary" onClick={open}>{imageUrl?__('Replace image','restatify-base'):__('Choose image','restatify-base')}</Button>}/></MediaUploadCheck>{imageUrl&&<Button variant="link" onClick={()=>setAttributes({imageUrl:''})}>{__('Remove image','restatify-base')}</Button>}</PanelBody></InspectorControls><div className={className} style={style}>{backgroundImageEnabled!==false&&overlayEnabled&&<div className="restatify-contact-bg-overlay" style={overlayStyle} aria-hidden="true"></div>}<div className="container"><div className="row justify-content-center"><div className="col-12 col-lg-11"><div className="content-wrapper"><p className="mbr-label mbr-fonts-style display-4">{label}</p><h2 className="mbr-section-title mbr-fonts-style display-2"><strong>{heading}</strong></h2><div className="row content-wrap"><div className="col-12 col-lg-6 card"><div className="items-wrapper"><ContactItem title={phoneLabel} value={phoneValue}/><ContactItem title={emailLabel} value={emailValue}/><ContactItem title={locationLabel} value={locationValue}/></div></div><div className="col-12 col-lg-6 card"><div className="image-wrapper">{imageUrl?<img src={imageUrl} alt="" loading="lazy"/>:<div className="image-placeholder" aria-label={__('Choose image','restatify-base')}></div>}</div></div></div></div></div></div></div></div></div>;
}

function Save({ attributes }) {
  const { backgroundImageEnabled, backgroundImageUrl, overlayEnabled, overlayColor, overlayOpacity, parallax, fullscreen, label, heading, phoneLabel, phoneValue, emailLabel, emailValue, locationLabel, locationValue, imageUrl } = attributes;
  const overlayStyle=getOverlayStyle(overlayEnabled, overlayColor, overlayOpacity); const blockProps=useBlockProps.save({className:['restatify-contact-block', backgroundImageEnabled!==false&&parallax?'is-parallax':'', fullscreen?'is-fullscreen':''].join(' '), style:getBackgroundStyle(backgroundImageEnabled, backgroundImageUrl)});
  return <div {...blockProps}>{backgroundImageEnabled!==false&&overlayEnabled&&<div className="restatify-contact-bg-overlay" style={overlayStyle} aria-hidden="true"></div>}<div className="container"><div className="row justify-content-center"><div className="col-12 col-lg-11"><div className="content-wrapper"><p className="mbr-label mbr-fonts-style display-4">{label}</p><h2 className="mbr-section-title mbr-fonts-style display-2"><strong>{heading}</strong></h2><div className="row content-wrap"><div className="col-12 col-lg-6 card"><div className="items-wrapper"><ContactItem title={phoneLabel} value={phoneValue}/><ContactItem title={emailLabel} value={emailValue}/><ContactItem title={locationLabel} value={locationValue}/></div></div><div className="col-12 col-lg-6 card"><div className="image-wrapper">{imageUrl&&<img src={imageUrl} alt="" loading="lazy"/>}</div></div></div></div></div></div></div></div>;
}

registerBlockType(metadata.name,{...metadata,edit:Edit,save:Save});
