import { __ } from '@wordpress/i18n';
import { useBlockProps, InspectorControls, MediaUpload, MediaUploadCheck } from '@wordpress/block-editor';
import { PanelBody, TextControl, ToggleControl, Button } from '@wordpress/components';
import { registerBlockType } from '@wordpress/blocks';
import metadata from './block.json';
import { BackgroundLayoutPanel, getBackgroundStyle, getOverlayStyle } from '../shared/background-layout-controls';
import './editor.css';
import './style.css';

function LogoControl({ index, value, setAttributes }) { const key=`logo${index}Url`; return <><p>{`Logo ${index}`}</p><MediaUploadCheck><MediaUpload onSelect={(m)=>setAttributes({[key]:m?.url||''})} allowedTypes={['image']} value={value} render={({open})=><Button variant="secondary" onClick={open}>{value?__('Replace logo','restatify-base'):__('Choose logo','restatify-base')}</Button>}/></MediaUploadCheck>{value&&<Button variant="link" onClick={()=>setAttributes({[key]:''})}>{__('Remove logo','restatify-base')}</Button>}</>; }

function Logos({ urls }) { return <div className="items-wrapper">{urls.map((u,i)=><div className="item" key={i}><div className="item-wrapper"><div className="item-img">{u?<img src={u} alt="" loading="lazy"/>:<div className="restatify-clients-placeholder" aria-hidden="true"></div>}</div></div></div>)}</div>; }

function Edit({ attributes, setAttributes }) { const { backgroundImageEnabled, backgroundImageUrl, overlayEnabled, overlayColor, overlayOpacity, parallax, fullscreen, label, showLabel, logo1Url, logo2Url, logo3Url, logo4Url, logo5Url, logo6Url } = attributes; const className=['restatify-clients-block', backgroundImageEnabled!==false&&parallax?'is-parallax':'', fullscreen?'is-fullscreen':''].join(' '); const style=getBackgroundStyle(backgroundImageEnabled, backgroundImageUrl); const overlayStyle=getOverlayStyle(overlayEnabled, overlayColor, overlayOpacity); const urls=[logo1Url,logo2Url,logo3Url,logo4Url,logo5Url,logo6Url]; return <div {...useBlockProps()}><InspectorControls><BackgroundLayoutPanel attributes={attributes} setAttributes={setAttributes}/><PanelBody title={__('Content','restatify-base')} initialOpen={false}><TextControl label={__('Label','restatify-base')} value={label} onChange={(v)=>setAttributes({label:v})}/></PanelBody><PanelBody title={__('Logos','restatify-base')} initialOpen={false}>{urls.map((v,i)=><LogoControl key={i} index={i+1} value={v} setAttributes={setAttributes}/>)}</PanelBody><PanelBody title={__('Content visibility','restatify-base')} initialOpen={false}><ToggleControl label={__('Show label','restatify-base')} checked={showLabel!==false} onChange={(v)=>setAttributes({showLabel:!!v})}/></PanelBody></InspectorControls><div className={className} style={style}>{backgroundImageEnabled!==false&&overlayEnabled&&<div className="restatify-clients-bg-overlay" style={overlayStyle} aria-hidden="true"></div>}<div className="container"><div className="row justify-content-center"><div className="col-12 col-lg-11"><div className="content-wrapper">{showLabel!==false&&<p className="mbr-label mbr-fonts-style display-4">{label}</p>}<Logos urls={urls}/></div></div></div></div></div></div>; }

function Save({ attributes }) { const { backgroundImageEnabled, backgroundImageUrl, overlayEnabled, overlayColor, overlayOpacity, parallax, fullscreen, label, showLabel, logo1Url, logo2Url, logo3Url, logo4Url, logo5Url, logo6Url } = attributes; const overlayStyle=getOverlayStyle(overlayEnabled, overlayColor, overlayOpacity); const blockProps=useBlockProps.save({className:['restatify-clients-block', backgroundImageEnabled!==false&&parallax?'is-parallax':'', fullscreen?'is-fullscreen':''].join(' '), style:getBackgroundStyle(backgroundImageEnabled, backgroundImageUrl)}); return <div {...blockProps}>{backgroundImageEnabled!==false&&overlayEnabled&&<div className="restatify-clients-bg-overlay" style={overlayStyle} aria-hidden="true"></div>}<div className="container"><div className="row justify-content-center"><div className="col-12 col-lg-11"><div className="content-wrapper">{showLabel!==false&&<p className="mbr-label mbr-fonts-style display-4">{label}</p>}<Logos urls={[logo1Url,logo2Url,logo3Url,logo4Url,logo5Url,logo6Url]}/></div></div></div></div></div>; }

registerBlockType(metadata.name,{...metadata,edit:Edit,save:Save});
