import { __ } from '@wordpress/i18n';
import { useBlockProps, InspectorControls, MediaUpload, MediaUploadCheck, __experimentalLinkControl as LinkControl } from '@wordpress/block-editor';
import { PanelBody, TextControl, ToggleControl, Button } from '@wordpress/components';
import { registerBlockType } from '@wordpress/blocks';
import metadata from './block.json';
import { BackgroundLayoutPanel, getBackgroundStyle, getOverlayStyle } from '../shared/background-layout-controls';
import { getUrlFromLinkValue } from '../shared/link-utils';
import './editor.css';
import './style.css';

function Edit({ attributes, setAttributes }) {
  const { backgroundImageEnabled, backgroundImageUrl, overlayEnabled, overlayColor, overlayOpacity, parallax, fullscreen, label, showLabel, heading, showHeading, buttonLabel, showButton, buttonUrl, imageUrl, showImage } = attributes;
  const className = ['restatify-insight-block', backgroundImageEnabled !== false && parallax ? 'is-parallax' : '', fullscreen ? 'is-fullscreen' : ''].join(' ');
  const style = getBackgroundStyle(backgroundImageEnabled, backgroundImageUrl);
  const overlayStyle = getOverlayStyle(overlayEnabled, overlayColor, overlayOpacity);
  const normalizedButtonUrl = buttonUrl === '#' ? '' : buttonUrl;
  return <div {...useBlockProps()}><InspectorControls><BackgroundLayoutPanel attributes={attributes} setAttributes={setAttributes}/><PanelBody title={__('Content','restatify-base')} initialOpen={false}><TextControl label={__('Label','restatify-base')} value={label} onChange={(v)=>setAttributes({label:v})}/><TextControl label={__('Heading','restatify-base')} value={heading} onChange={(v)=>setAttributes({heading:v})}/><TextControl label={__('Button label','restatify-base')} value={buttonLabel} onChange={(v)=>setAttributes({buttonLabel:v})}/><p>{__('Button link','restatify-base')}</p><LinkControl value={{url: normalizedButtonUrl || ''}} onChange={(next)=>setAttributes({buttonUrl:getUrlFromLinkValue(next)})} settings={[]}/></PanelBody><PanelBody title={__('Image','restatify-base')} initialOpen={false}><MediaUploadCheck><MediaUpload onSelect={(media)=>setAttributes({imageUrl:media?.url||''})} allowedTypes={['image']} value={imageUrl} render={({open})=><Button variant="secondary" onClick={open}>{imageUrl?__('Replace image','restatify-base'):__('Choose image','restatify-base')}</Button>}/></MediaUploadCheck>{imageUrl&&<Button variant="link" onClick={()=>setAttributes({imageUrl:''})}>{__('Remove image','restatify-base')}</Button>}</PanelBody><PanelBody title={__('Content visibility','restatify-base')} initialOpen={false}><ToggleControl label={__('Show label','restatify-base')} checked={showLabel!==false} onChange={(v)=>setAttributes({showLabel:!!v})}/><ToggleControl label={__('Show heading','restatify-base')} checked={showHeading!==false} onChange={(v)=>setAttributes({showHeading:!!v})}/><ToggleControl label={__('Show button','restatify-base')} checked={showButton!==false} onChange={(v)=>setAttributes({showButton:!!v})}/><ToggleControl label={__('Show image','restatify-base')} checked={showImage!==false} onChange={(v)=>setAttributes({showImage:!!v})}/></PanelBody></InspectorControls><div className={className} style={style}>{backgroundImageEnabled!==false&&overlayEnabled&&<div className="restatify-insight-bg-overlay" style={overlayStyle} aria-hidden="true"></div>}<div className="container"><div className="row justify-content-center"><div className="col-12 col-lg-8"><div className="content-wrapper">{showLabel!==false&&<p className="mbr-label mbr-fonts-style display-4">{label}</p>}{showHeading!==false&&<h2 className="mbr-section-title mbr-fonts-style display-2"><strong>{heading}</strong></h2>}{showButton!==false&&buttonLabel&&<div className="mbr-section-btn"><a className="btn btn-black display-7" href={buttonUrl||'#'}>{buttonLabel}</a></div>}</div>{showImage!==false&&<div className="image-wrapper">{imageUrl?<img src={imageUrl} alt="" loading="lazy"/>:<div className="image-placeholder" aria-label={__('Choose image','restatify-base')}></div>}</div>}</div></div></div></div></div>;
}

function Save({ attributes }) {
  const { backgroundImageEnabled, backgroundImageUrl, overlayEnabled, overlayColor, overlayOpacity, parallax, fullscreen, label, showLabel, heading, showHeading, buttonLabel, showButton, buttonUrl, imageUrl, showImage } = attributes;
  const overlayStyle = getOverlayStyle(overlayEnabled, overlayColor, overlayOpacity);
  const blockProps = useBlockProps.save({ className: ['restatify-insight-block', backgroundImageEnabled !== false && parallax ? 'is-parallax' : '', fullscreen ? 'is-fullscreen' : ''].join(' '), style: getBackgroundStyle(backgroundImageEnabled, backgroundImageUrl) });
  return <div {...blockProps}>{backgroundImageEnabled!==false&&overlayEnabled&&<div className="restatify-insight-bg-overlay" style={overlayStyle} aria-hidden="true"></div>}<div className="container"><div className="row justify-content-center"><div className="col-12 col-lg-8"><div className="content-wrapper">{showLabel!==false&&<p className="mbr-label mbr-fonts-style display-4">{label}</p>}{showHeading!==false&&<h2 className="mbr-section-title mbr-fonts-style display-2"><strong>{heading}</strong></h2>}{showButton!==false&&buttonLabel&&<div className="mbr-section-btn"><a className="btn btn-black display-7" href={buttonUrl||'#'}>{buttonLabel}</a></div>}</div>{showImage!==false&&<div className="image-wrapper">{imageUrl&&<img src={imageUrl} alt="" loading="lazy"/>}</div>}</div></div></div></div>;
}

registerBlockType(metadata.name,{...metadata,edit:Edit,save:Save});
